version: "3.8"

services:
  warp_proxy1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=your_secret_key
      - API_USERNAME=admin
      - API_PASSWORD=password
    ports:
      - "5001:5000"

  warp_proxy2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=your_secret_key
      - API_USERNAME=admin
      - API_PASSWORD=password
    ports:
      - "5002:5000"

  dante1:
    build:
      context: .
      dockerfile: Dockerfile.dante
    ports:
      - "1081:1081"

  dante2:
    build:
      context: .
      dockerfile: Dockerfile.dante
    ports:
      - "1082:1080"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9090:80"
    depends_on:
      - warp_proxy1
      - warp_proxy2
